# Generated by Django 6.0.2 on 2026-02-14 09:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur_creation', models.CharField(blank=True, max_length=100, null=True)),
                ('utilisateur_modification', models.CharField(blank=True, max_length=100, null=True)),
                ('code_national', models.CharField(max_length=50, unique=True)),
                ('code_interne', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('denomination', models.CharField(max_length=500)),
                ('denomination_commerciale', models.CharField(blank=True, max_length=500, null=True)),
                ('forme_pharmaceutique', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('dci', models.CharField(blank=True, max_length=200, null=True)),
                ('classe_therapeutique', models.CharField(blank=True, max_length=200, null=True)),
                ('conditionnement', models.CharField(max_length=200)),
                ('unite_mesure', models.CharField(max_length=20)),
                ('quantite_par_unite', models.IntegerField(default=1)),
                ('stock_securite', models.IntegerField(default=0)),
                ('stock_alerte', models.IntegerField(default=0)),
                ('duree_peremption_mois', models.IntegerField(blank=True, null=True)),
                ('temperature_conservation', models.CharField(blank=True, max_length=50, null=True)),
                ('necessite_chaine_froid', models.BooleanField(default=False)),
                ('type_produit', models.CharField(choices=[('MEDICAMENT', 'Médicament'), ('DISPOSITIF_MEDICAL', 'Dispositif médical'), ('CONSOMMABLE', 'Consommable'), ('REACTIF', 'Réactif'), ('GAZ_MEDICAL', 'Gaz médical')], default='MEDICAMENT', max_length=50)),
                ('categorie_surveillance', models.CharField(choices=[('NORMAL', 'Normal'), ('PSYCHOTROPE', 'Psychotrope'), ('STUPEFIANT', 'Stupéfiant'), ('PRODUIT_SANG', 'Produit sanguin'), ('ONCOLOGIE', 'Oncologie')], default='NORMAL', max_length=50)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('RETIRE', 'Retiré'), ('RUPTURE_NATIONALE', 'Rupture nationale')], default='ACTIF', max_length=20)),
                ('fabricant', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_amm', models.CharField(blank=True, max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur_creation', models.CharField(blank=True, max_length=100, null=True)),
                ('utilisateur_modification', models.CharField(blank=True, max_length=100, null=True)),
                ('code_service', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type_service', models.CharField(max_length=50)),
                ('specialite', models.CharField(max_length=100)),
                ('nombre_lits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_ordre', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LotProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur_creation', models.CharField(blank=True, max_length=100, null=True)),
                ('utilisateur_modification', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_lot', models.CharField(max_length=100)),
                ('date_fabrication', models.DateField(blank=True, null=True)),
                ('date_peremption', models.DateField()),
                ('date_reception', models.DateField()),
                ('quantite_initiale', models.IntegerField()),
                ('quantite_actuelle', models.IntegerField()),
                ('quantite_reservee', models.IntegerField(default=0)),
                ('statut', models.CharField(default='DISPONIBLE', max_length=30)),
                ('prix_unitaire_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
            options={
                'unique_together': {('produit', 'numero_lot')},
            },
        ),
    ]
