# Generated by Django 6.0.2 on 2026-02-14 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur_creation', models.CharField(blank=True, max_length=100, null=True)),
                ('utilisateur_modification', models.CharField(blank=True, max_length=100, null=True)),
                ('code_fournisseur', models.CharField(max_length=50, unique=True)),
                ('raison_sociale', models.CharField(max_length=300)),
                ('sigle', models.CharField(blank=True, max_length=50, null=True)),
                ('type_fournisseur', models.CharField(choices=[('FABRICANT', 'Fabricant'), ('GROSSISTE', 'Grossiste'), ('IMPORTATEUR', 'Importateur'), ('ETABLISSEMENT_PUBLIC', 'Etablissement Public')], max_length=50)),
                ('categorie', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('wilaya', models.CharField(blank=True, max_length=100, null=True)),
                ('commune', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nom_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(default='ACTIF', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur_creation', models.CharField(blank=True, max_length=100, null=True)),
                ('utilisateur_modification', models.CharField(blank=True, max_length=100, null=True)),
                ('code_magasin', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type_magasin', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('PSYCHOTROPES', 'Psychotropes'), ('CHAINE_FROID', 'Chaine froid'), ('CONSOMMABLES', 'Consommables')], max_length=50)),
                ('batiment', models.CharField(blank=True, max_length=100, null=True)),
                ('etage', models.CharField(blank=True, max_length=50, null=True)),
                ('niveau_securite', models.CharField(default='STANDARD', max_length=30)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='service',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='nombre_lits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='type_service',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CommandeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur_creation', models.CharField(blank=True, max_length=100, null=True)),
                ('utilisateur_modification', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_commande', models.CharField(max_length=100, unique=True)),
                ('statut', models.CharField(default='BROUILLON', max_length=30)),
                ('priorite', models.CharField(default='NORMALE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneCommandeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur_creation', models.CharField(blank=True, max_length=100, null=True)),
                ('utilisateur_modification', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite_demandee', models.IntegerField()),
                ('quantite_livree', models.IntegerField(default=0)),
                ('statut', models.CharField(default='EN_ATTENTE', max_length=30)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.commandeservice')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur_creation', models.CharField(blank=True, max_length=100, null=True)),
                ('utilisateur_modification', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_mouvement', models.CharField(max_length=100, unique=True)),
                ('type_mouvement', models.CharField(choices=[('ENTREE_ACHAT', 'Entrée Achat'), ('SORTIE_SERVICE', 'Sortie Service'), ('TRANSFERT', 'Transfert'), ('PERIME', 'Périmé'), ('AJUSTEMENT', 'Ajustement')], max_length=50)),
                ('quantite', models.IntegerField()),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lotproduit')),
                ('magasin_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees', to='core.magasin')),
                ('magasin_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties', to='core.magasin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
