# Generated by Django 6.0.2 on 2026-02-14 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_utilisateur_can_add_commandes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource', models.CharField(max_length=50)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_change', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['resource', 'codename'],
            },
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_add_commandes',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_add_fournisseurs',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_add_lots',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_add_magasins',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_add_mouvements',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_add_produits',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_add_services',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_add_users',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_change_commandes',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_change_fournisseurs',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_change_lots',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_change_magasins',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_change_mouvements',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_change_produits',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_change_services',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_change_users',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_delete_commandes',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_delete_fournisseurs',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_delete_lots',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_delete_magasins',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_delete_mouvements',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_delete_produits',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_delete_services',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_delete_users',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_view_commandes',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_view_fournisseurs',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_view_lots',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_view_magasins',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_view_mouvements',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_view_produits',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_view_services',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='can_view_users',
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='core.permission')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='core.role'),
        ),
    ]
