# Generated by Django 6.0.2 on 2026-02-14 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_permission_remove_utilisateur_can_add_commandes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='core.service'),
        ),
    ]
