# Generated by Django 6.0.2 on 2026-02-14 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_utilisateur_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur_creation', models.CharField(blank=True, max_length=100, null=True)),
                ('utilisateur_modification', models.CharField(blank=True, max_length=100, null=True)),
                ('categorie', models.CharField(choices=[('COMMANDE', 'Commande'), ('STOCK', 'Stock'), ('PRODUIT', 'Produit'), ('UTILISATEUR', 'Utilisateur'), ('SYSTEM', 'System')], max_length=20)),
                ('action', models.CharField(choices=[('CREATE', 'Creation'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VALIDATE', 'Validation'), ('ANNUL', 'Annulation'), ('LIVRE', 'Livraison'), ('RECEPTION', 'Reception')], max_length=20)),
                ('description', models.TextField()),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('entity_description', models.CharField(blank=True, max_length=255, null=True)),
                ('ancien_statut', models.CharField(blank=True, max_length=50, null=True)),
                ('nouveau_statut', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'ordering': ['-date_creation'],
            },
        ),
    ]
