# Generated by Django 6.0.2 on 2026-03-01 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='core.magasin'),
        ),
    ]
