# Generated by Django 6.0.2 on 2026-03-01 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_service_magasin"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lotproduit",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="lotproduit",
            name="magasin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.magasin",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lotproduit",
            unique_together={("produit", "numero_lot", "magasin")},
        ),
        migrations.RunSQL(
            sql="""
                UPDATE core_lotproduit 
                SET magasin_id = (SELECT id FROM core_magasin WHERE type_magasin='PRINCIPAL' LIMIT 1)
                WHERE magasin_id IS NULL;
            """,
            reverse_sql="",
        ),
    ]
