# Generated by Django 6.0.2 on 2026-03-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lotproduit_magasin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magasin',
            name='type_magasin',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal'), ('HORS_CIRCLE', 'Hors Circuit (Urgence Grave)'), ('URGENCE', 'Urgence'), ('PSYCHOTROPES', 'Psychotropes'), ('CHAINE_FROID', 'Chaine froid'), ('CONSOMMABLES', 'Consommables')], max_length=50),
        ),
    ]
